spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #     routes:
      #       - id: match-service
      #         uri: lb://MATCH-SERVICE
      #         predicates:
      #           - Path=/match-service/**
      #
      #       - id: team-service
      #         uri: lb://TEAM-SERVICE
      #         predicates:
      #           - Path=/team-service/**

  application:
    name: gateway

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/flash-score

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8089
